version: '3.8'

services:
  # Standalone Qdrant server for multi-client support
  qdrant-server:
    image: qdrant/qdrant:v1.7.0
    container_name: qdrant-server-dev
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    volumes:
      - ~/.claude/alunai-clarity/qdrant:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    healthcheck:
      test: ["CMD-SHELL", "timeout 3 bash -c '</dev/tcp/localhost/6333' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  alunai-clarity-dev:
    build:
      context: ..
      dockerfile: local-dev/Dockerfile.dev
    container_name: alunai-clarity-mcp-dev
    depends_on:
      qdrant-server:
        condition: service_healthy
    volumes:
      # Mount the entire project for live code updates
      - ..:/app
      # Persistent data volume (mounted after code to preserve data)
      - ~/.claude/alunai-clarity/app-data:/app/data
      # Cache volume for faster rebuilds
      - ~/.claude/alunai-clarity/pip-cache:/root/.cache/pip
    environment:
      - PYTHONUNBUFFERED=1
      - CLARITY_LOG_LEVEL=DEBUG
      - CLARITY_DEBUG_MODE=true
      - QDRANT_URL=http://qdrant-server:6333
      - MEMORY_CONFIG_PATH=/app/data/config.json
    ports:
      # Expose ports for debugging/monitoring if needed
      - "8000:8000"  # FastAPI debug server
    stdin_open: true
    tty: true
    # Restart policy for development
    restart: unless-stopped
    # Health check to ensure the server is running
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Standalone Qdrant service for advanced debugging
  qdrant-standalone:
    image: qdrant/qdrant:v1.7.0
    container_name: qdrant-standalone-dev
    ports:
      - "6335:6333"  # HTTP API (alternative port)
      - "6336:6334"  # gRPC API (alternative port)
    volumes:
      - qdrant-standalone-data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    profiles:
      - standalone-qdrant

volumes:
  qdrant-standalone-data:
    driver: local